config = {
    "customer_risk_score_data_raw_to_curated": {
        "sql_path": "customer_riskscore_data.sql",
        "partition_cols": ["year", "month", "day"],
        "catalog": {
            "dynamodb_keys_customer_id_s": "string",
            "updated_timestamp": "timestamp",
            "date": "string",
            "year": "string",
            "month": "string",
            "day": "string",
            "timestamp_extracted": "timestamp",
            "items_new_0_type": "string",
            "items_new_0_converted_currency": "string",
            "items_new_0_local_currency": "string",
            "items_new_1_type": "string",
            "items_new_1_converted_currency": "string",
            "items_new_1_local_currency": "string",
            "items_new_2_type": "string",
            "items_new_2_converted_currency": "string",
            "items_new_2_local_currency": "string",
            "items_new_3_type": "string",
            "items_new_3_converted_currency": "string",
            "items_new_3_local_currency": "string",
            "items_new_4_type": "string",
            "items_new_4_converted_currency": "string",
            "items_new_4_local_currency": "string",
            "items_new_5_type": "string",
            "items_new_5_converted_currency": "string",
            "items_new_5_local_currency": "string",
            "items_new_6_type": "string",
            "items_new_6_converted_currency": "string",
            "items_new_6_local_currency": "string",
            "items_new_7_type": "string",
            "items_new_7_converted_currency": "string",
            "items_new_7_local_currency": "string",
            "items_new_8_type": "string",
            "items_new_8_converted_currency": "string",
            "items_new_8_local_currency": "string",
            "items_new_9_type": "string",
            "items_new_9_converted_currency": "string",
            "items_new_9_local_currency": "string",
            "items_new_10_type": "string",
            "items_new_10_converted_currency": "string",
            "items_new_10_local_currency": "string",
            "items_new_11_type": "string",
            "items_new_11_converted_currency": "string",
            "items_new_11_local_currency": "string",
            "items_new_12_type": "string",
            "items_new_12_converted_currency": "string",
            "items_new_12_local_currency": "string",
            "items_new_13_type": "string",
            "items_new_13_converted_currency": "string",
            "items_new_13_local_currency": "string",
            "items_new_14_type": "string",
            "items_new_14_converted_currency": "string",
            "items_new_14_local_currency": "string",
            "items_new_15_type": "string",
            "items_new_15_converted_currency": "string",
            "items_new_15_local_currency": "string",
            "items_new_16_type": "string",
            "items_new_16_converted_currency": "string",
            "items_new_16_local_currency": "string",
            "items_new_17_type": "string",
            "items_new_17_converted_currency": "string",
            "items_new_17_local_currency": "string",
            "items_new_18_type": "string",
            "items_new_18_converted_currency": "string",
            "items_new_18_local_currency": "string",
            "items_new_19_type": "string",
            "items_new_19_converted_currency": "string",
            "items_new_19_local_currency": "string",
            "items_new_20_type": "string",
            "items_new_20_converted_currency": "string",
            "items_new_20_local_currency": "string",
            "items_new_21_type": "string",
            "items_new_21_converted_currency": "string",
            "items_new_21_local_currency": "string",
            "items_new_22_type": "string",
            "items_new_22_converted_currency": "string",
            "items_new_22_local_currency": "string",
            "items_new_23_type": "string",
            "items_new_23_converted_currency": "string",
            "items_new_23_local_currency": "string",
            "items_new_24_type": "string",
            "items_new_24_converted_currency": "string",
            "items_new_24_local_currency": "string",
            "items_new_25_type": "string",
            "items_new_25_converted_currency": "string",
            "items_new_25_local_currency": "string",
            "items_new_26_type": "string",
            "items_new_26_converted_currency": "string",
            "items_new_26_local_currency": "string",
            "items_new_27_type": "string",
            "items_new_27_converted_currency": "string",
            "items_new_27_local_currency": "string",
            "items_new_28_type": "string",
            "items_new_28_converted_currency": "string",
            "items_new_28_local_currency": "string",
            "items_new_29_type": "string",
            "items_new_29_converted_currency": "string",
            "items_new_29_local_currency": "string",
            "total_net_worth_converted_currency": "string",
            "total_net_worth_local_currency": "string",
        },
        "column_comments": {
            "dynamodb_keys_customer_id_s": "customer  id",
            "timestamp_extracted": "The timestamp when data was extracted for the journey.",
            "date": "date",
            "items_new_0_converted_currency": "combination of currency code +total value from + total value to for item 0 ",
            "items_new_1_converted_currency": "combination of currency code +total value from + total value to for item 1 ",
            "items_new_2_converted_currency": "combination of currency code +total value from + total value to for item 2 ",
            "items_new_3_converted_currency": "combination of currency code +total value from + total value to for item 3 ",
            "items_new_4_converted_currency": "combination of currency code +total value from + total value to for item 4 ",
            "items_new_5_converted_currency": "combination of currency code +total value from + total value to for item 5 ",
            "items_new_6_converted_currency": "combination of currency code +total value from + total value to for item 6 ",
            "items_new_7_converted_currency": "combination of currency code +total value from + total value to for item 7 ",
            "items_new_8_converted_currency": "combination of currency code +total value from + total value to for item 8 ",
            "items_new_9_converted_currency": "combination of currency code +total value from + total value to for item 9 ",
            "items_new_10_converted_currency": "combination of currency code +total value from + total value to for item 10 ",
            "items_new_11_converted_currency": "combination of currency code +total value from + total value to for item 11 ",
            "items_new_12_converted_currency": "combination of currency code +total value from + total value to for item 12 ",
            "items_new_13_converted_currency": "combination of currency code +total value from + total value to for item 13 ",
            "items_new_14_converted_currency": "combination of currency code +total value from + total value to for item 14 ",
            "items_new_15_converted_currency": "combination of currency code +total value from + total value to for item 15 ",
            "items_new_16_converted_currency": "combination of currency code +total value from + total value to for item 16 ",
            "items_new_17_converted_currency": "combination of currency code +total value from + total value to for item 17 ",
            "items_new_18_converted_currency": "combination of currency code +total value from + total value to for item 18 ",
            "items_new_19_converted_currency": "combination of currency code +total value from + total value to for item 19 ",
            "items_new_20_converted_currency": "combination of currency code +total value from + total value to for item 20 ",
            "items_new_21_converted_currency": "combination of currency code +total value from + total value to for item 21 ",
            "items_new_22_converted_currency": "combination of currency code +total value from + total value to for item 22 ",
            "items_new_23_converted_currency": "combination of currency code +total value from + total value to for item 23 ",
            "items_new_24_converted_currency": "combination of currency code +total value from + total value to for item 24 ",
            "items_new_25_converted_currency": "combination of currency code +total value from + total value to for item 25 ",
            "items_new_26_converted_currency": "combination of currency code +total value from + total value to for item 26 ",
            "items_new_27_converted_currency": "combination of currency code +total value from + total value to for item 27 ",
            "items_new_28_converted_currency": "combination of currency code +total value from + total value to for item 28 ",
            "items_new_29_converted_currency": "combination of currency code +total value from + total value to for item 29 ",
            "Status": "contain the value if the row will be considered as Income_Salary or Wealth",
        },
    }
}
