SELECT       
    COALESCE(dynamodb_keys_customer_id_s,dynamodb_new_image_customer_id_s) as dynamodb_keys_customer_id_s,
    dynamodb_new_image_updated_at_n as "updated_timestamp",
    date (dynamodb_new_image_updated_at_n) as "date",

    -- Item 0
    dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_0_m_type_s AS "items_new_0_type",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_0_m_total_value_m_converted_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_0_m_total_value_m_converted_currency_m_from_n as varchar), '_',
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_0_m_total_value_m_converted_currency_m_to_n as varchar)) AS "items_new_0_converted_currency",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_0_m_total_value_m_local_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_0_m_total_value_m_local_currency_m_from_n as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_0_m_total_value_m_local_currency_m_to_n as varchar)) AS "items_new_0_local_currency",
    -- Item 1
    dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_1_m_type_s AS "items_new_1_type",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_1_m_total_value_m_converted_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_1_m_total_value_m_converted_currency_m_from_n as varchar), '_',
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_1_m_total_value_m_converted_currency_m_to_n as varchar)) AS "items_new_1_converted_currency",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_1_m_total_value_m_local_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_1_m_total_value_m_local_currency_m_from_n as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_1_m_total_value_m_local_currency_m_to_n as varchar)) AS "items_new_1_local_currency",
    -- Item 2
    dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_2_m_type_s AS "items_new_2_type",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_2_m_total_value_m_converted_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_2_m_total_value_m_converted_currency_m_from_n as varchar), '_',
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_2_m_total_value_m_converted_currency_m_to_n as varchar)) AS "items_new_2_converted_currency",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_2_m_total_value_m_local_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_2_m_total_value_m_local_currency_m_from_n as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_2_m_total_value_m_local_currency_m_to_n as varchar)) AS "items_new_2_local_currency",
    -- Item 3
    dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_3_m_type_s AS "items_new_3_type",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_3_m_total_value_m_converted_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_3_m_total_value_m_converted_currency_m_from_n as varchar), '_',
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_3_m_total_value_m_converted_currency_m_to_n as varchar)) AS "items_new_3_converted_currency",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_3_m_total_value_m_local_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_3_m_total_value_m_local_currency_m_from_n as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_3_m_total_value_m_local_currency_m_to_n as varchar)) AS "items_new_3_local_currency",
    -- Item 4
    dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_4_m_type_s AS "items_new_4_type",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_4_m_total_value_m_converted_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_4_m_total_value_m_converted_currency_m_from_n as varchar), '_',
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_4_m_total_value_m_converted_currency_m_to_n as varchar)) AS "items_new_4_converted_currency",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_4_m_total_value_m_local_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_4_m_total_value_m_local_currency_m_from_n as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_4_m_total_value_m_local_currency_m_to_n as varchar)) AS "items_new_4_local_currency",
    -- Item 5
    dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_5_m_type_s AS "items_new_5_type",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_5_m_total_value_m_converted_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_5_m_total_value_m_converted_currency_m_from_n as varchar), '_',
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_5_m_total_value_m_converted_currency_m_to_n as varchar)) AS "items_new_5_converted_currency",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_5_m_total_value_m_local_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_5_m_total_value_m_local_currency_m_from_n as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_5_m_total_value_m_local_currency_m_to_n as varchar)) AS "items_new_5_local_currency",
    -- Item 6
    dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_6_m_type_s AS "items_new_6_type",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_6_m_total_value_m_converted_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_6_m_total_value_m_converted_currency_m_from_n as varchar), '_',
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_6_m_total_value_m_converted_currency_m_to_n as varchar)) AS "items_new_6_converted_currency",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_6_m_total_value_m_local_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_6_m_total_value_m_local_currency_m_from_n as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_6_m_total_value_m_local_currency_m_to_n as varchar)) AS "items_new_6_local_currency",
    -- Item 7
    dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_7_m_type_s AS "items_new_7_type",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_7_m_total_value_m_converted_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_7_m_total_value_m_converted_currency_m_from_n as varchar), '_',
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_7_m_total_value_m_converted_currency_m_to_n as varchar)) AS "items_new_7_converted_currency",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_7_m_total_value_m_local_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_7_m_total_value_m_local_currency_m_from_n as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_7_m_total_value_m_local_currency_m_to_n as varchar)) AS "items_new_7_local_currency",
    -- Item 8
    dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_8_m_type_s AS "items_new_8_type",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_8_m_total_value_m_converted_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_8_m_total_value_m_converted_currency_m_from_n as varchar), '_',
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_8_m_total_value_m_converted_currency_m_to_n as varchar)) AS "items_new_8_converted_currency",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_8_m_total_value_m_local_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_8_m_total_value_m_local_currency_m_from_n as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_8_m_total_value_m_local_currency_m_to_n as varchar)) AS "items_new_8_local_currency",
    -- Item 9
    dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_9_m_type_s AS "items_new_9_type",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_9_m_total_value_m_converted_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_9_m_total_value_m_converted_currency_m_from_n as varchar), '_',
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_9_m_total_value_m_converted_currency_m_to_n as varchar)) AS "items_new_9_converted_currency",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_9_m_total_value_m_local_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_9_m_total_value_m_local_currency_m_from_n as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_9_m_total_value_m_local_currency_m_to_n as varchar)) AS "items_new_9_local_currency",
    -- Item 10
    dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_10_m_type_s AS "items_new_10_type",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_10_m_total_value_m_converted_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_10_m_total_value_m_converted_currency_m_from_n as varchar), '_',
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_10_m_total_value_m_converted_currency_m_to_n as varchar)) AS "items_new_10_converted_currency",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_10_m_total_value_m_local_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_10_m_total_value_m_local_currency_m_from_n as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_10_m_total_value_m_local_currency_m_to_n as varchar)) AS "items_new_10_local_currency",
    -- Item 11
    dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_11_m_type_s AS "items_new_11_type",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_11_m_total_value_m_converted_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_11_m_total_value_m_converted_currency_m_from_n as varchar), '_',
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_11_m_total_value_m_converted_currency_m_to_n as varchar)) AS "items_new_11_converted_currency",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_11_m_total_value_m_local_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_11_m_total_value_m_local_currency_m_from_n as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_11_m_total_value_m_local_currency_m_to_n as varchar)) AS "items_new_11_local_currency",
    -- Item 12
    dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_12_m_type_s AS "items_new_12_type",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_12_m_total_value_m_converted_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_12_m_total_value_m_converted_currency_m_from_n as varchar), '_',
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_12_m_total_value_m_converted_currency_m_to_n as varchar)) AS "items_new_12_converted_currency",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_12_m_total_value_m_local_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_12_m_total_value_m_local_currency_m_from_n as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_12_m_total_value_m_local_currency_m_to_n as varchar)) AS "items_new_12_local_currency",
    -- Item 13
    dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_13_m_type_s AS "items_new_13_type",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_13_m_total_value_m_converted_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_13_m_total_value_m_converted_currency_m_from_n as varchar), '_',
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_13_m_total_value_m_converted_currency_m_to_n as varchar)) AS "items_new_13_converted_currency",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_13_m_total_value_m_local_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_13_m_total_value_m_local_currency_m_from_n as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_13_m_total_value_m_local_currency_m_to_n as varchar)) AS "items_new_13_local_currency",
    -- Item 14
    dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_14_m_type_s AS "items_new_14_type",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_14_m_total_value_m_converted_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_14_m_total_value_m_converted_currency_m_from_n as varchar), '_',
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_14_m_total_value_m_converted_currency_m_to_n as varchar)) AS "items_new_14_converted_currency",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_14_m_total_value_m_local_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_14_m_total_value_m_local_currency_m_from_n as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_14_m_total_value_m_local_currency_m_to_n as varchar)) AS "items_new_14_local_currency",
    -- Item 15
    dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_15_m_type_s AS "items_new_15_type",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_15_m_total_value_m_converted_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_15_m_total_value_m_converted_currency_m_from_n as varchar), '_',
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_15_m_total_value_m_converted_currency_m_to_n as varchar)) AS "items_new_15_converted_currency",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_15_m_total_value_m_local_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_15_m_total_value_m_local_currency_m_from_n as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_15_m_total_value_m_local_currency_m_to_n as varchar)) AS "items_new_15_local_currency",
    -- Item 16
    dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_16_m_type_s AS "items_new_16_type",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_16_m_total_value_m_converted_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_16_m_total_value_m_converted_currency_m_from_n as varchar), '_',
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_16_m_total_value_m_converted_currency_m_to_n as varchar)) AS "items_new_16_converted_currency",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_16_m_total_value_m_local_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_16_m_total_value_m_local_currency_m_from_n as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_16_m_total_value_m_local_currency_m_to_n as varchar)) AS "items_new_16_local_currency",
    -- Item 17
    dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_17_m_type_s AS "items_new_17_type",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_17_m_total_value_m_converted_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_17_m_total_value_m_converted_currency_m_from_n as varchar), '_',
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_17_m_total_value_m_converted_currency_m_to_n as varchar)) AS "items_new_17_converted_currency",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_17_m_total_value_m_local_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_17_m_total_value_m_local_currency_m_from_n as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_17_m_total_value_m_local_currency_m_to_n as varchar)) AS "items_new_17_local_currency",
    -- Item 18
    dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_18_m_type_s AS "items_new_18_type",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_18_m_total_value_m_converted_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_18_m_total_value_m_converted_currency_m_from_n as varchar), '_',
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_18_m_total_value_m_converted_currency_m_to_n as varchar)) AS "items_new_18_converted_currency",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_18_m_total_value_m_local_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_18_m_total_value_m_local_currency_m_from_n as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_18_m_total_value_m_local_currency_m_to_n as varchar)) AS "items_new_18_local_currency",
    -- Item 19
    dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_19_m_type_s AS "items_new_19_type",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_19_m_total_value_m_converted_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_19_m_total_value_m_converted_currency_m_from_n as varchar), '_',
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_19_m_total_value_m_converted_currency_m_to_n as varchar)) AS "items_new_19_converted_currency",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_19_m_total_value_m_local_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_19_m_total_value_m_local_currency_m_from_n as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_19_m_total_value_m_local_currency_m_to_n as varchar)) AS "items_new_19_local_currency",
    -- Item 20
    dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_20_m_type_s AS "items_new_20_type",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_20_m_total_value_m_converted_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_20_m_total_value_m_converted_currency_m_from_n as varchar), '_',
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_20_m_total_value_m_converted_currency_m_to_n as varchar)) AS "items_new_20_converted_currency",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_20_m_total_value_m_local_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_20_m_total_value_m_local_currency_m_from_n as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_20_m_total_value_m_local_currency_m_to_n as varchar)) AS "items_new_20_local_currency",
    -- Item 21
    dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_21_m_type_s AS "items_new_21_type",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_21_m_total_value_m_converted_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_21_m_total_value_m_converted_currency_m_from_n as varchar), '_',
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_21_m_total_value_m_converted_currency_m_to_n as varchar)) AS "items_new_21_converted_currency",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_21_m_total_value_m_local_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_21_m_total_value_m_local_currency_m_from_n as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_21_m_total_value_m_local_currency_m_to_n as varchar)) AS "items_new_21_local_currency",
    -- Item 22
    dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_22_m_type_s AS "items_new_22_type",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_22_m_total_value_m_converted_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_22_m_total_value_m_converted_currency_m_from_n as varchar), '_',
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_22_m_total_value_m_converted_currency_m_to_n as varchar)) AS "items_new_22_converted_currency",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_22_m_total_value_m_local_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_22_m_total_value_m_local_currency_m_from_n as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_22_m_total_value_m_local_currency_m_to_n as varchar)) AS "items_new_22_local_currency",
    -- Item 23
    dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_23_m_type_s AS "items_new_23_type",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_23_m_total_value_m_converted_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_23_m_total_value_m_converted_currency_m_from_n as varchar), '_',
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_23_m_total_value_m_converted_currency_m_to_n as varchar)) AS "items_new_23_converted_currency",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_23_m_total_value_m_local_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_23_m_total_value_m_local_currency_m_from_n as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_23_m_total_value_m_local_currency_m_to_n as varchar)) AS "items_new_23_local_currency",
    -- Item 24
    dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_24_m_type_s AS "items_new_24_type",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_24_m_total_value_m_converted_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_24_m_total_value_m_converted_currency_m_from_n as varchar), '_',
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_24_m_total_value_m_converted_currency_m_to_n as varchar)) AS "items_new_24_converted_currency",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_24_m_total_value_m_local_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_24_m_total_value_m_local_currency_m_from_n as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_24_m_total_value_m_local_currency_m_to_n as varchar)) AS "items_new_24_local_currency",
    -- Item 25
    dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_25_m_type_s AS "items_new_25_type",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_25_m_total_value_m_converted_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_25_m_total_value_m_converted_currency_m_from_n as varchar), '_',
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_25_m_total_value_m_converted_currency_m_to_n as varchar)) AS "items_new_25_converted_currency",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_25_m_total_value_m_local_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_25_m_total_value_m_local_currency_m_from_n as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_25_m_total_value_m_local_currency_m_to_n as varchar)) AS "items_new_25_local_currency",
    -- Item 26
    dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_26_m_type_s AS "items_new_26_type",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_26_m_total_value_m_converted_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_26_m_total_value_m_converted_currency_m_from_n as varchar), '_',
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_26_m_total_value_m_converted_currency_m_to_n as varchar)) AS "items_new_26_converted_currency",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_26_m_total_value_m_local_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_26_m_total_value_m_local_currency_m_from_n as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_26_m_total_value_m_local_currency_m_to_n as varchar)) AS "items_new_26_local_currency",
    -- Item 27
    dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_27_m_type_s AS "items_new_27_type",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_27_m_total_value_m_converted_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_27_m_total_value_m_converted_currency_m_from_n as varchar), '_',
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_27_m_total_value_m_converted_currency_m_to_n as varchar)) AS "items_new_27_converted_currency",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_27_m_total_value_m_local_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_27_m_total_value_m_local_currency_m_from_n as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_27_m_total_value_m_local_currency_m_to_n as varchar)) AS "items_new_27_local_currency",
    -- Item 28
    dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_28_m_type_s AS "items_new_28_type",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_28_m_total_value_m_converted_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_28_m_total_value_m_converted_currency_m_from_n as varchar), '_',
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_28_m_total_value_m_converted_currency_m_to_n as varchar)) AS "items_new_28_converted_currency",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_28_m_total_value_m_local_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_28_m_total_value_m_local_currency_m_from_n as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_28_m_total_value_m_local_currency_m_to_n as varchar)) AS "items_new_28_local_currency",
 	-- Item 29
    dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_29_m_type_s AS "items_new_29_type",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_29_m_total_value_m_converted_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_29_m_total_value_m_converted_currency_m_from_n as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_29_m_total_value_m_converted_currency_m_to_n as varchar)) AS "items_new_29_converted_currency",
    CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_29_m_total_value_m_local_currency_m_currency_code_s as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_29_m_total_value_m_local_currency_m_from_n as varchar), '_', 
           cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_items_l_29_m_total_value_m_local_currency_m_to_n as varchar)) AS "items_new_29_local_currency",
	-- Total net worth
	CONCAT(cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_total_estimated_net_worth_m_converted_currency_m_currency_code_s as varchar),'_',
	    cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_total_estimated_net_worth_m_converted_currency_m_from_n as varchar),'_',
	    cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_total_estimated_net_worth_m_converted_currency_m_to_n as varchar) ) AS "total_net_worth_converted_currency",
	CONCAT(cast (dynamodb_new_image_customer_m_source_of_wealth_assets_m_total_estimated_net_worth_m_local_currency_m_currency_code_s as varchar),'_', 
	    cast (dynamodb_new_image_customer_m_source_of_wealth_assets_m_total_estimated_net_worth_m_local_currency_m_from_n as varchar),'_',
	    cast (dynamodb_new_image_customer_m_source_of_wealth_assets_m_total_estimated_net_worth_m_local_currency_m_to_n as varchar) ) AS "total_net_worth_local_currency",
	-- Additional columns
       cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_total_estimated_net_worth_m_currency_code_s as varchar) as estimated_net_worth_currency_code,
       cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_total_estimated_net_worth_m_from_n as varchar) as estimated_net_worth_min_local,
       cast(dynamodb_new_image_customer_m_source_of_wealth_assets_m_total_estimated_net_worth_m_to_n as varchar) as estimated_net_worth_max_local
from "datalake_raw"."dynamo_sls_riskscore"
WHERE
    dynamodb_new_image_updated_at_n IS NOT NULL
    AND CAST(dynamodb_new_image_updated_at_n AS VARCHAR) != ''