column_comments = {
    "cards_paymentology_fees": {
        "py__rid_settlement": "The paymentology rid settlement",
        "py__account_id": "The paymentology account id",
        "py__token": "The paymentology token",
        "py__account_external_reference": "The paymentology account external reference",
        "py__file_id": "The paymentology file id",
        "py__transaction_id": "The paymentology transaction id",
        "py__network": "The paymentology network",
        "py__mtid": "The paymentology mtid",
        "py__created_date": "The paymentology created date",
        "py__matched_status": "The paymentology matched status",
        "py__is_debit": "The paymentology is debit or not",
        "py__settlement_note": "The paymentology settlement note",
        "de3_1__cardholder_transaction_type": "The card holder transaction type",
        "de3_2__cardholder_from_account_type_code": "The card holder from account type code",
        "de3_3__cardholder_to_account_type_code": "The card holder to account type code",
        "de4__transaction_amount": "The transaction amount",
        "de5__reconciliation_amount": "The reconciliation amount",
        "de9__conversion_rate_reconciliation": "The conversion rate reconciliation",
        "de24__function_code": "The function code",
        "de25__message_reason_code": "The message reason code",
        "de26__merchant_category_code": "The merchant category code",
        "de30_1__original_amount_transaction": "The original amount transaction",
        "de30_2__original_amount_reconciliation": "The original amount reconciliation",
        "de31__acquirer_reference_data": "The acquirer reference data",
        "de32__acquiring_institution_id_code": "The acquiring institution id code",
        "de33__forwarding_institution_id_code": "The forwarding institution id code",
        "de38__approval_code": "The approval code",
        "de41__card_acceptor_terminal_id": "The card acceptor terminal id",
        "de42__card_acceptor_id_code": "The card acceptor id code",
        "de43_1__card_acceptor_name": "The card acceptor name",
        "de43_2__card_acceptor_street_address": "The card acceptor street address",
        "de43_3__card_acceptor_city": "The card acceptor city",
        "de43_4__card_acceptor_zip_code": "The card acceptor zip code",
        "de43_5__card_acceptor_state_code": "The card acceptor state code",
        "de43_6__card_acceptor_country_code": "The card acceptor country code",
        "de48_0002__gcms_product_identifier": "The gcms product identifier",
        "de48_0003__licensed_product_identifier": "The licensed product identifier",
        "de48_0023__terminal_type": "The terminal type",
        "de48_0025_1__message_reversal_indicator": "The message reversal indicator",
        "de48_0105__network_file_reference": "The network file reference",
        "de48_0158_1__card_program_identifier": "The card program identifier",
        "de48_0158_2__business_service_arrangement_type_code": "The business service arrangement type code",
        "de48_0158_3__business_service_id_code": "The business service id code",
        "de48_0158_4__interchange_rate_designaor": "The interchange rate designaor",
        "de48_0158_5__central_site_business_date": "The central site business date",
        "de48_0158_6__business_cycle": "The business cycle",
        "de48_0158_7__card_acceptor_classification_override_indicator": "The card acceptor classification override indicator",
        "de48_0158_8__product_class_override_indicator": "The product class override indicator",
        "de48_0158_9__corporate_incentive_rates_apply_indicator": "The corporate incentive rates apply indicator",
        "de48_0158_10__special_conditions_indicator": "The special conditions indicator",
        "de48_0158_11__mc_assigned_id_override_indicator": "The mc assigned id override indicator",
        "de48_0158_12__account_level_management_account_category_code": "The account level management account category code",
        "de48_0158_13__rate_indicator": "The rate indicator",
        "de48_0158_14__masterpass_incentive_indicator": "The masterpass incentive indicator",
        "de48_159_3__settlement_service_level_code": "The settlement service level code",
        "de48_159_6__reconciliation_date": "The reconciliation date",
        "de48_159_7__reconciliation_cycle": "The reconciliation cycle",
        "de48_159_8__settlement_date": "The settlement date",
        "de48_159_9__settlement_cycle": "The settlement cycle",
        "de49__currency_code_transaction": "The currency code transaction",
        "de50__currency_code_reconciliation": "The currency code reconciliation",
        "de63__transaction_life_cycle_id": "The transaction life cycle id",
        "de71__message_number": "The message number",
        "de72__data_record": "The data record",
        "de73__action_date": "The action date",
        "de93__transaction_destination_institution_id": "The transaction destination institution id",
        "de94__transaction_originator_institution_id": "The transaction originator institution id",
        "de100__receiving_institution_id": "The receiving institution id",
        "source_file": "The source file",
    },
    "cards_paymentology_interchange": {
        "py__rid_settlement": "The paymentology rid settlement",
        "py__rid_authorization": "The paymentology rid authorization",
        "py__account_id": "The paymentology account id",
        "py__token": "The paymentology token",
        "py__account_external_reference": "The paymentology account external reference",
        "py__file_id": "The paymentology file id",
        "py__transaction_id": "The paymentology transaction id",
        "py__network": "The paymentology network",
        "py__mtid": "The paymentology mtid",
        "py__created_date": "The paymentology created date",
        "py__is_debit": "The paymentology is debit or not",
        "de48_0105__network_file_reference": "The network file reference",
        "de48_0146_2__fee_processing_code": "The fee processing code",
        "de48_0146_3__fee_settlement_indicator": "The fee settlement indicator",
        "de48_0146_4__fee_currency_code": "The fee currency code",
        "de48_0146_5__fee_interchange_amount": "The fee interchange amount",
        "de48_0146_6__fee_currency_code_reconciliation": "The fee currency code reconciliation",
        "de48_0146_7__fee_interchange_amount_reconciliation": "The fee interchange amount reconciliation",
        "de48_0158_1__card_program_identifier": "The card program identifier",
        "de48_0158_2__business_service_arrangement_type_code": "The business service arrangement type code",
        "de48_0158_3__business_service_id_code": "The business service id code",
        "de48_0158_4__interchange_rate_designaor": "The interchange rate designaor",
        "de48_0158_5__central_site_business_date": "The central site business date",
        "de48_0158_6__business_cycle": "The business cycle",
        "de48_0158_7__card_acceptor_classification_override_indicator": "The card acceptor classification override indicator",
        "de48_0158_8__product_class_override_indicator": "The product class override indicator",
        "de48_0158_9__corporate_incentive_rates_apply_indicator": "The corporate incentive rates apply indicator",
        "de48_0158_10__special_conditions_indicator": "The special conditions indicator",
        "de48_0158_11__mc_assigned_id_override_indicator": "The mc assigned id override indicator",
        "de48_0158_12__account_level_management_account_category_code": "The account level management account category code",
        "de48_0158_13__rate_indicator": "The rate indicator",
        "de48_0158_14__masterpass_incentive_indicator": "The masterpass incentive indicator",
        "de48_159_6__reconciliation_date": "The reconciliation date",
        "de48_159_7__reconciliation_cycle": "The reconciliation cycle",
        "de48_159_8__settlement_date": "The settlement date",
        "de48_159_9__settlement_cycle": "The settlement cycle",
        "de71__message_number": "The message number",
        "de100__receiving_institution_id": "The receiving institution id",
        "source_file": "The source file",
    },
    "cards_paymentology_presentments": {
        "py__rid_settlement": "The paymentology rid settlement",
        "py__rid_authorization": "The paymentology rid authorization",
        "py__account_id": "The paymentology account id",
        "py__token": "The paymentology token",
        "py__account_external_reference": "The paymentology account external reference",
        "py__file_id": "The paymentology file id",
        "py__transaction_id": "The paymentology transaction id",
        "py__network": "The paymentology network",
        "py__mtid": "The paymentology mtid",
        "py__created_date": "The paymentology created date",
        "py__matched_status": "The paymentology matched status",
        "py__is_debit": "The paymentology is debit or not",
        "py__product_id": "The paymentology product id",
        "py__product_name": "The paymentology product name",
        "py__settlement_note": "The paymentology settlement note",
        "de3_1__cardholder_transaction_type": "The card holder transaction type",
        "de3_2__cardholder_from_account_type_code": "The card holder from account type code",
        "de3_3__cardholder_to_account_type_code": "The card holder to account type code",
        "de4__transaction_amount": "The transaction amount",
        "de5__reconciliation_amount": "The reconciliation amount",
        "de6__billing_amount": "The billing amount",
        "de9__conversion_rate_reconciliation": "The conversion rate reconciliation",
        "de10__conversion_rate_billing": "The conversion rate billing",
        "de12__transaction_date_time": "The transaction date time",
        "de22_6__card_present_data": "The card present data",
        "de22_7__card_data_input_mode": "The card data input mode",
        "de22_8__cardholder_authentication_method": "The card holder authentication method",
        "de23__card_sequence_number": "The card sequence number",
        "de24__function_code": "The function code",
        "de25__message_reason_code": "The message reason code",
        "de26__merchant_category_code": "The merchant category code",
        "de30_1__original_amount_transaction": "The original amount transaction",
        "de30_2__original_amount_reconciliation": "The original amount reconciliation",
        "de31__acquirer_reference_data": "The acquirer reference data",
        "de32__acquiring_institution_id_code": "The acquiring institution id code",
        "de33__forwarding_institution_id_code": "The forwarding institution id code",
        "de37__retrieval_reference_number": "The retrieval reference number",
        "de38__approval_code": "The approval code",
        "de40__service_code": "The service code",
        "de41__card_acceptor_terminal_id": "The card acceptor terminal id",
        "de42__card_acceptor_id_code": "The card acceptor id code",
        "de43_1__card_acceptor_name": "The card acceptor name",
        "de43_2__card_acceptor_street_address": "The card acceptor street address",
        "de43_3__card_acceptor_city": "The card acceptor city",
        "de43_4__card_acceptor_zip_code": "The card acceptor zip code",
        "de43_5__card_acceptor_state_code": "The card acceptor state code",
        "de43_6__card_acceptor_country_code": "The card acceptor country code",
        "de48_0002__gcms_product_identifier": "The gcms product identifier",
        "de48_0003__licensed_product_identifier": "The licensed product identifier",
        "de48_0023__terminal_type": "The terminal type",
        "de48_0025_1__message_reversal_indicator": "The message reversal indicator",
        "de48_0105__network_file_reference": "The network file reference",
        "de48_0158_1__card_program_identifier": "The card program identifier",
        "de48_0158_2__business_service_arrangement_type_code": "The business service arrangement type code",
        "de48_0158_3__business_service_id_code": "The business service id code",
        "de48_0158_4__interchange_rate_designaor": "The interchange rate designaor",
        "de48_0158_5__central_site_business_date": "The central site business date",
        "de48_0158_6__business_cycle": "The business cycle",
        "de48_0158_7__card_acceptor_classification_override_indicator": "The card acceptor classification override indicator",
        "de48_0158_8__product_class_override_indicator": "The product class override indicator",
        "de48_0158_9__corporate_incentive_rates_apply_indicator": "The corporate incentive rates apply indicator",
        "de48_0158_10__special_conditions_indicator": "The special conditions indicator",
        "de48_0158_11__mc_assigned_id_override_indicator": "The mc assigned id override indicator",
        "de48_0158_12__account_level_management_account_category_code": "The account level management account category code",
        "de48_0158_13__rate_indicator": "The rate indicator",
        "de48_0158_14__masterpass_incentive_indicator": "The masterpass incentive indicator",
        "de48_159_3__settlement_service_level_code": "The settlement service level code",
        "de48_159_6__reconciliation_date": "The reconciliation date",
        "de48_159_7__reconciliation_cycle": "The reconciliation cycle",
        "de48_159_8__settlement_date": "The settlement date",
        "de48_159_9__settlement_cycle": "The settlement cycle",
        "de48_0177_1__cross_border_indicator": "The cross border indicator",
        "de48_0177_2__currency_indicator": "The currency indicator",
        "de49__currency_code_transaction": "The currency code transaction",
        "de50__currency_code_reconciliation": "The currency code reconciliation",
        "de51__currency_code_billing": "The currency code billing",
        "de54_2__additional_amount_type": "The additional amount type",
        "de54_3__additional_amount_currncy_code": "The additional amount currncy code",
        "de54_4__additional_amount_sign": "The additional amount sign",
        "de54_5__additional_amount": "The additional amount",
        "de63__transaction_life_cycle_id": "The transaction life cycle id",
        "de71__message_number": "The message number",
        "de72__data_record": "The data record",
        "de73__action_date": "The action date",
        "de93__transaction_destination_institution_id": "The transaction destination institution id",
        "de94__transaction_originator_institution_id": "The transaction originator institution id",
        "de100__receiving_institution_id": "The receiving institution id",
        "de111__amount_currency_conversion_assessment": "The amount currency conversion assessment",
        "source_file": "The source file",
    },
}

schemas = {
    "cards_paymentology_fees": {
        "py__rid_settlement": "string",
        "py__account_id": "double",
        "py__token": "double",
        "py__account_external_reference": "string",
        "py__file_id": "string",
        "py__transaction_id": "string",
        "py__network": "string",
        "py__mtid": "string",
        "py__created_date": "string",
        "py__matched_status": "string",
        "py__is_debit": "string",
        "py__settlement_note": "string",
        "de3_1__cardholder_transaction_type": "string",
        "de3_2__cardholder_from_account_type_code": "string",
        "de3_3__cardholder_to_account_type_code": "string",
        "de4__transaction_amount": "string",
        "de5__reconciliation_amount": "string",
        "de9__conversion_rate_reconciliation": "string",
        "de24__function_code": "string",
        "de25__message_reason_code": "string",
        "de26__merchant_category_code": "string",
        "de30_1__original_amount_transaction": "string",
        "de30_2__original_amount_reconciliation": "string",
        "de31__acquirer_reference_data": "string",
        "de32__acquiring_institution_id_code": "string",
        "de33__forwarding_institution_id_code": "string",
        "de38__approval_code": "string",
        "de41__card_acceptor_terminal_id": "string",
        "de42__card_acceptor_id_code": "string",
        "de43_1__card_acceptor_name": "string",
        "de43_2__card_acceptor_street_address": "string",
        "de43_3__card_acceptor_city": "string",
        "de43_4__card_acceptor_zip_code": "string",
        "de43_5__card_acceptor_state_code": "string",
        "de43_6__card_acceptor_country_code": "string",
        "de48_0002__gcms_product_identifier": "string",
        "de48_0003__licensed_product_identifier": "string",
        "de48_0023__terminal_type": "string",
        "de48_0025_1__message_reversal_indicator": "string",
        "de48_0105__network_file_reference": "string",
        "de48_0158_1__card_program_identifier": "string",
        "de48_0158_2__business_service_arrangement_type_code": "string",
        "de48_0158_3__business_service_id_code": "string",
        "de48_0158_4__interchange_rate_designaor": "string",
        "de48_0158_5__central_site_business_date": "string",
        "de48_0158_6__business_cycle": "string",
        "de48_0158_7__card_acceptor_classification_override_indicator": "string",
        "de48_0158_8__product_class_override_indicator": "string",
        "de48_0158_9__corporate_incentive_rates_apply_indicator": "string",
        "de48_0158_10__special_conditions_indicator": "string",
        "de48_0158_11__mc_assigned_id_override_indicator": "string",
        "de48_0158_12__account_level_management_account_category_code": "string",
        "de48_0158_13__rate_indicator": "string",
        "de48_0158_14__masterpass_incentive_indicator": "string",
        "de48_159_3__settlement_service_level_code": "string",
        "de48_159_6__reconciliation_date": "string",
        "de48_159_7__reconciliation_cycle": "string",
        "de48_159_8__settlement_date": "string",
        "de48_159_9__settlement_cycle": "string",
        "de49__currency_code_transaction": "string",
        "de50__currency_code_reconciliation": "string",
        "de63__transaction_life_cycle_id": "string",
        "de71__message_number": "string",
        "de72__data_record": "string",
        "de73__action_date": "string",
        "de93__transaction_destination_institution_id": "string",
        "de94__transaction_originator_institution_id": "string",
        "de100__receiving_institution_id": "string",
        "source_file": "string",
    },
    "cards_paymentology_interchange": {
        "py__rid_settlement": "string",
        "py__rid_authorization": "string",
        "py__account_id": "string",
        "py__token": "string",
        "py__account_external_reference": "string",
        "py__file_id": "string",
        "py__transaction_id": "string",
        "py__network": "string",
        "py__mtid": "string",
        "py__created_date": "string",
        "py__is_debit": "string",
        "de48_0105__network_file_reference": "string",
        "de48_0146_2__fee_processing_code": "string",
        "de48_0146_3__fee_settlement_indicator": "string",
        "de48_0146_4__fee_currency_code": "string",
        "de48_0146_5__fee_interchange_amount": "string",
        "de48_0146_6__fee_currency_code_reconciliation": "string",
        "de48_0146_7__fee_interchange_amount_reconciliation": "string",
        "de48_0158_1__card_program_identifier": "string",
        "de48_0158_2__business_service_arrangement_type_code": "string",
        "de48_0158_3__business_service_id_code": "string",
        "de48_0158_4__interchange_rate_designaor": "string",
        "de48_0158_5__central_site_business_date": "string",
        "de48_0158_6__business_cycle": "string",
        "de48_0158_7__card_acceptor_classification_override_indicator": "string",
        "de48_0158_8__product_class_override_indicator": "string",
        "de48_0158_9__corporate_incentive_rates_apply_indicator": "string",
        "de48_0158_10__special_conditions_indicator": "string",
        "de48_0158_11__mc_assigned_id_override_indicator": "string",
        "de48_0158_12__account_level_management_account_category_code": "string",
        "de48_0158_13__rate_indicator": "string",
        "de48_0158_14__masterpass_incentive_indicator": "string",
        "de48_159_6__reconciliation_date": "string",
        "de48_159_7__reconciliation_cycle": "string",
        "de48_159_8__settlement_date": "string",
        "de48_159_9__settlement_cycle": "string",
        "de71__message_number": "string",
        "de100__receiving_institution_id": "string",
        "source_file": "string",
    },
    "cards_paymentology_presentments": {
        "py__rid_settlement": "string",
        "py__rid_authorization": "string",
        "py__account_id": "string",
        "py__token": "string",
        "py__account_external_reference": "string",
        "py__file_id": "string",
        "py__transaction_id": "string",
        "py__network": "string",
        "py__mtid": "string",
        "py__created_date": "string",
        "py__matched_status": "string",
        "py__is_debit": "string",
        "py__product_id": "string",
        "py__product_name": "string",
        "py__settlement_note": "string",
        "de3_1__cardholder_transaction_type": "string",
        "de3_2__cardholder_from_account_type_code": "string",
        "de3_3__cardholder_to_account_type_code": "string",
        "de4__transaction_amount": "string",
        "de5__reconciliation_amount": "string",
        "de6__billing_amount": "string",
        "de9__conversion_rate_reconciliation": "string",
        "de10__conversion_rate_billing": "string",
        "de12__transaction_date_time": "string",
        "de22_6__card_present_data": "string",
        "de22_7__card_data_input_mode": "string",
        "de22_8__cardholder_authentication_method": "string",
        "de23__card_sequence_number": "string",
        "de24__function_code": "string",
        "de25__message_reason_code": "string",
        "de26__merchant_category_code": "string",
        "de30_1__original_amount_transaction": "string",
        "de30_2__original_amount_reconciliation": "string",
        "de31__acquirer_reference_data": "string",
        "de32__acquiring_institution_id_code": "string",
        "de33__forwarding_institution_id_code": "string",
        "de37__retrieval_reference_number": "string",
        "de38__approval_code": "string",
        "de40__service_code": "string",
        "de41__card_acceptor_terminal_id": "string",
        "de42__card_acceptor_id_code": "string",
        "de43_1__card_acceptor_name": "string",
        "de43_2__card_acceptor_street_address": "string",
        "de43_3__card_acceptor_city": "string",
        "de43_4__card_acceptor_zip_code": "string",
        "de43_5__card_acceptor_state_code": "string",
        "de43_6__card_acceptor_country_code": "string",
        "de48_0002__gcms_product_identifier": "string",
        "de48_0003__licensed_product_identifier": "string",
        "de48_0023__terminal_type": "string",
        "de48_0025_1__message_reversal_indicator": "string",
        "de48_0105__network_file_reference": "string",
        "de48_0158_1__card_program_identifier": "string",
        "de48_0158_2__business_service_arrangement_type_code": "string",
        "de48_0158_3__business_service_id_code": "string",
        "de48_0158_4__interchange_rate_designaor": "string",
        "de48_0158_5__central_site_business_date": "string",
        "de48_0158_6__business_cycle": "string",
        "de48_0158_7__card_acceptor_classification_override_indicator": "string",
        "de48_0158_8__product_class_override_indicator": "string",
        "de48_0158_9__corporate_incentive_rates_apply_indicator": "string",
        "de48_0158_10__special_conditions_indicator": "string",
        "de48_0158_11__mc_assigned_id_override_indicator": "string",
        "de48_0158_12__account_level_management_account_category_code": "string",
        "de48_0158_13__rate_indicator": "string",
        "de48_0158_14__masterpass_incentive_indicator": "string",
        "de48_159_3__settlement_service_level_code": "string",
        "de48_159_6__reconciliation_date": "string",
        "de48_159_7__reconciliation_cycle": "string",
        "de48_159_8__settlement_date": "string",
        "de48_159_9__settlement_cycle": "string",
        "de48_0177_1__cross_border_indicator": "string",
        "de48_0177_2__currency_indicator": "string",
        "de49__currency_code_transaction": "string",
        "de50__currency_code_reconciliation": "string",
        "de51__currency_code_billing": "string",
        "de54_2__additional_amount_type": "string",
        "de54_3__additional_amount_currncy_code": "string",
        "de54_4__additional_amount_sign": "string",
        "de54_5__additional_amount": "string",
        "de63__transaction_life_cycle_id": "string",
        "de71__message_number": "string",
        "de72__data_record": "string",
        "de73__action_date": "string",
        "de93__transaction_destination_institution_id": "string",
        "de94__transaction_originator_institution_id": "string",
        "de100__receiving_institution_id": "string",
        "de111__amount_currency_conversion_assessment": "string",
        "source_file": "string",
    },
}
