column_comments = {
    "customer_timeline_detail":{
        "dynamo_user_key": "the id of the user from dynamo",
        "dynamo_updated_at": "Updated At",
        "dynamo_user_status": "Status of user",
        "dynamodb_individual_m_nationality_country_code_s": "Status of user",
        "phone_number_populated": "is phone number populated",
        "email_populated": "is email populated",
        "nickname_populated": "is nickname populated",
        "address_country_code": "",
        "address_status": "",
        "asset_types": "",
        "estimated_assets_value": "",
        "income_sources": "",
        "monthly_income": "",
        "reason_for_opening_account": "",
        "identity_verification_status": "",
        "tax_ids_country_code": "",
        "brand_id": "the identifier for the brand partner",
        "tax_id_value_populated": "",
        "tax_id_skip_reason_populated": "",
        "external_onfido_applicant_id": "",
        "identity_document_type": "",
        "age_range": "",
        "age": "customers age in years",
        "dynamodb_new_gid": "gender male or femal populated",
        "push_notifications_m_marketing": "dynamo new image push notifications",
        "sms_notifications_m_marketing": "dynamo new image sms notifications",
        "email_notifications_m_marketing": "dynamo new image email notifications",
        "first_join_date": "the identifier for the first_join_date",
        "date": "date",
    }
}

schemas = {
    "customer_timeline_detail":{
        "dynamo_user_key": "string",
        "dynamo_updated_at": "string",
        "dynamo_user_status": "string",
        "dynamodb_individual_m_nationality_country_code_s": "string",
        "phone_number_populated": "boolean",
        "email_populated": "boolean",
        "nickname_populated": "boolean",
        "address_country_code": "string",
        "address_status": "string",
        "asset_types": "string",
        "estimated_assets_value": "string",
        "income_sources": "string",
        "monthly_income": "string",
        "reason_for_opening_account": "string",
        "identity_verification_status": "string",
        "tax_ids_country_code": "string",
        "brand_id": "string",
        "tax_id_value_populated": "boolean",
        "tax_id_skip_reason_populated": "boolean",
        "external_onfido_applicant_id": "string",
        "identity_document_type": "string",
        "age_range": "string",
        "age": "int",
        "dynamodb_new_gid": "string",
        "push_notifications_m_marketing": "boolean",
        "sms_notifications_m_marketing": "boolean",
        "email_notifications_m_marketing": "boolean",
        "first_join_date": "string",
        "date": "date",
    }
}
