column_comments = {
    "customer_mambu":{
        "mambu_outbound_card_transaction_amount": "Money sent with Card",
        "mambu_outbound_nomo_transaction_amount": "Money sent with Nomo",
        "mambu_account": "",
        "mambu_account_id": "",
        "mambu_account_type": "The type of the mambu account",
        "mambu_account_total_balance": "The total balance of the acocunt",
        "mambu_deposit_accounts_encoded_key": "",
        "mambu_account_holder_key": "The Mambu account holder key",
        "mambu_account_currency_code": "The currency of the account",
        "mambu_account_state": "The state of the account in Mambu",
        "mambu_account_last_modified_date":"",
        "mambu_account_approved_date":"",
        "mambu_account_activation_date":"",
        "dynamo_user_key": "the id of the user from dynamo",
        "mambu_user_state": "The state of the user from Mambu",
        "mambu_client_id": "The client id from Mambu clients table", 
        "mambu_clients_encoded_key": "",
        "dynamo_card_ordered": "Whether the card has been ordered",
        "dynamo_card_state": "",
        "date":"Date of when the ETL ran",
    },
}

schemas = {
    "customer_mambu":{
        "mambu_outbound_card_transaction_amount": "float",
        "mambu_outbound_nomo_transaction_amount": "float",
        "mambu_account": "string",
        "mambu_account_id": "string",
        "mambu_account_type": "string",
        "mambu_account_total_balance": "double",
        "mambu_deposit_accounts_encoded_key": "string",
        "mambu_account_holder_key": "string",
        "mambu_account_currency_code": "string",
        "mambu_account_state": "string",
        "mambu_account_last_modified_date":"timestamp",
        "mambu_account_approved_date":"timestamp",
        "mambu_account_activation_date":"timestamp",
        "dynamo_user_key": "string",
        "mambu_user_state": "string",
        "mambu_client_id": "string", 
        "mambu_clients_encoded_key": "string",
        "dynamo_card_ordered": "boolean",
        "dynamo_card_state": "string",
        "date":"date",
    },
}
