config = {
    "customer_risk_form_data_raw_to_curated": {
        "sql_path": "customer_risk_form_data.sql",
        "partition_cols": ["date"],
        "catalog": {
            "dynamodb_new_image_created_at_n"	:"timestamp",
            "dynamodb_new_image_customer_id_s"	:"string",
            "dynamodb_new_image_form_data_m_countries_of_personal_links_l_0_s"	:"string",
            "dynamodb_new_image_form_data_m_customer_circumstances_l_0_s"	:"string",
            "dynamodb_new_image_form_data_m_customer_occupations_l_0_s"	:"string",
            "dynamodb_new_image_form_data_m_expected_monthly_value_of_transactions_inbound_m_currency_code_s"	:"string",
            "dynamodb_new_image_form_data_m_expected_monthly_value_of_transactions_inbound_m_from_n"	:"int",
            "dynamodb_new_image_form_data_m_expected_monthly_value_of_transactions_inbound_m_to_n"	:"int",
            "dynamodb_new_image_form_data_m_expected_monthly_value_of_transactions_outbound_m_currency_code_s"	:"string",
            "dynamodb_new_image_form_data_m_expected_monthly_value_of_transactions_outbound_m_from_n"	:"int",
            "dynamodb_new_image_form_data_m_expected_monthly_value_of_transactions_outbound_m_to_n"	:"int",
            "dynamodb_new_image_form_data_m_pep_positions_l_0_m_pep_position_s"	:"string",
            "dynamodb_new_image_updated_at_n"	:"timestamp",
            "dynamodb_new_image_form_data_m_countries_of_personal_links_l_1_s"	:"string",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_0_m_country_code_s"	:"string",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_0_m_frequency_s"	:"string",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_0_m_total_income_m_currency_code_s"	:"string",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_0_m_total_income_m_from_n"	:"int",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_0_m_total_income_m_to_n"	:"int",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_0_m_type_s"	:"string",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_1_m_frequency_s"	:"string",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_1_m_total_income_m_currency_code_s"	:"string",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_1_m_total_income_m_from_n"	:"int",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_1_m_total_income_m_to_n"	:"int",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_1_m_type_s"	:"string",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_2_m_country_code_s"	:"string",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_2_m_frequency_s"	:"string",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_2_m_total_income_m_currency_code_s"	:"string",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_2_m_total_income_m_from_n"	:"int",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_2_m_total_income_m_to_n"	:"int",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_2_m_type_s"	:"string",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_3_m_country_code_s"	:"string",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_3_m_frequency_s"	:"string",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_3_m_total_income_m_currency_code_s"	:"string",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_3_m_total_income_m_from_n"	:"int",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_3_m_total_income_m_to_n"	:"int",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_3_m_type_s"	:"string",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_4_m_country_code_s"	:"string",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_4_m_frequency_s"	:"string",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_4_m_total_income_m_currency_code_s"	:"string",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_4_m_total_income_m_from_n"	:"int",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_4_m_total_income_m_to_n"	:"int",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_4_m_type_s"	:"string",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_5_m_country_code_s"	:"string",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_5_m_frequency_s"	:"string",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_5_m_total_income_m_currency_code_s"	:"string",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_5_m_total_income_m_from_n"	:"int",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_5_m_total_income_m_to_n"	:"int",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_5_m_type_s"	:"string",
            "dynamodb_new_image_form_data_m_customer_circumstances_l_1_s"	:"string",
            "dynamodb_new_image_form_data_m_customer_occupations_l_1_s"	:"string",
            "dynamodb_new_image_form_data_m_customer_occupations_l_2_s"	:"string",
            "dynamodb_new_image_form_data_m_expected_transaction_from_m_expected_m_amount_m_currency_code_s"	:"string",
            "dynamodb_new_image_form_data_m_expected_transaction_from_m_expected_m_amount_m_from_n"	:"int",
            "dynamodb_new_image_form_data_m_expected_transaction_from_m_expected_m_amount_m_to_n"	:"int",
            "dynamodb_new_image_form_data_m_expected_transaction_from_m_expected_m_frequency_s"	:"string",
            "dynamodb_new_image_form_data_m_expected_transaction_from_m_my_bank_acc_l_0_m_amount_m_currency_code_s"	:"string",
            "dynamodb_new_image_form_data_m_expected_transaction_from_m_my_bank_acc_l_0_m_amount_m_from_n"	:"int",
            "dynamodb_new_image_form_data_m_expected_transaction_from_m_my_bank_acc_l_0_m_amount_m_to_n"	:"int",
            "dynamodb_new_image_form_data_m_expected_transaction_from_m_my_bank_acc_l_0_m_country_code_s"	:"string",
            "dynamodb_new_image_form_data_m_expected_transaction_from_m_my_bank_acc_l_0_m_frequency_s"	:"string",
            "dynamodb_new_image_form_data_m_expected_transaction_from_m_my_bank_acc_l_1_m_amount_m_currency_code_s"	:"string",
            "dynamodb_new_image_form_data_m_expected_transaction_from_m_my_bank_acc_l_1_m_amount_m_from_n"	:"int",
            "dynamodb_new_image_form_data_m_expected_transaction_from_m_my_bank_acc_l_1_m_amount_m_to_n"	:"int",
            "dynamodb_new_image_form_data_m_expected_transaction_from_m_my_bank_acc_l_1_m_country_code_s"	:"string",
            "dynamodb_new_image_form_data_m_expected_transaction_from_m_my_bank_acc_l_1_m_frequency_s"	:"string",
            "dynamodb_new_image_form_data_m_expected_transaction_to_m_amount_m_currency_code_s"	:"string",
            "dynamodb_new_image_form_data_m_expected_transaction_to_m_amount_m_from_n"	:"int",
            "dynamodb_new_image_form_data_m_expected_transaction_to_m_amount_m_to_n"	:"int",
            "dynamodb_new_image_form_data_m_expected_transaction_to_m_frequency_s"	:"string",
            "dynamodb_new_image_form_data_m_expected_transaction_to_m_use_reasons_l_0_s"	:"string",
            "dynamodb_new_image_form_data_m_expected_transaction_to_m_use_reasons_l_1_s"	:"string",
            "dynamodb_new_image_form_data_m_expected_transaction_to_m_use_reasons_l_2_s"	:"string",
            "dynamodb_new_image_form_data_m_expected_transaction_to_m_use_reasons_l_3_s"	:"string",
            "dynamodb_new_image_form_data_m_expected_transaction_to_m_use_reasons_l_4_s"	:"string",
            "dynamodb_new_image_form_data_m_expected_transaction_to_m_use_reasons_l_5_s"	:"string",
            "dynamodb_new_image_form_data_m_supporting_documents_m_send_bool"	:"boolean",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_1_m_country_code_s"	:"string",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_1_m_total_value_of_properties_m_currency_code_s"	:"string",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_1_m_total_value_of_properties_m_from_n"	:"int",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_1_m_total_value_of_properties_m_to_n"	:"int",
            "dynamodb_new_image_form_data_m_countries_of_personal_links_l_2_s"	:"string",
            "dynamodb_new_image_form_data_m_expected_transaction_from_m_other_bank_acc_l_0_m_amount_m_currency_code_s"	:"string",
            "dynamodb_new_image_form_data_m_expected_transaction_from_m_other_bank_acc_l_0_m_amount_m_from_n"	:"int",
            "dynamodb_new_image_form_data_m_expected_transaction_from_m_other_bank_acc_l_0_m_amount_m_to_n"	:"int",
            "dynamodb_new_image_form_data_m_expected_transaction_from_m_other_bank_acc_l_0_m_country_code_s"	:"string",
            "dynamodb_new_image_form_data_m_expected_transaction_from_m_other_bank_acc_l_0_m_frequency_s"	:"string",
            "dynamodb_new_image_form_data_m_expected_transaction_from_m_other_bank_acc_l_0_m_source_name_s"	:"string",
            "dynamodb_new_image_form_data_m_expected_transaction_from_m_other_bank_acc_l_0_m_type_s"	:"string",
            "dynamodb_new_image_form_data_m_pep_positions_l_0_m_state_corporation_name_s"	:"string",
            "dynamodb_new_image_form_data_m_supporting_documents_m_certified_assets_l_0_s"	:"string",
            "dynamodb_new_image_form_data_m_supporting_documents_m_three_month_bank_statement_l_0_s"	:"string",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_0_m_other_value_s"	:"string",
            "dynamodb_new_image_form_data_m_expected_transaction_to_m_other_reason_s"	:"string",
            "dynamodb_new_image_form_data_m_expected_transaction_to_m_use_reasons_l_6_s"	:"string",
            "dynamodb_new_image_form_data_m_countries_of_personal_links_l_3_s"	:"string",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_2_m_other_value_s"	:"string",
            "dynamodb_new_image_form_data_m_expected_transaction_from_m_other_bank_acc_l_1_m_amount_m_currency_code_s"	:"string",
            "dynamodb_new_image_form_data_m_expected_transaction_from_m_other_bank_acc_l_1_m_amount_m_from_n"	:"int",
            "dynamodb_new_image_form_data_m_expected_transaction_from_m_other_bank_acc_l_1_m_amount_m_to_n"	:"int",
            "dynamodb_new_image_form_data_m_expected_transaction_from_m_other_bank_acc_l_1_m_country_code_s"	:"string",
            "dynamodb_new_image_form_data_m_expected_transaction_from_m_other_bank_acc_l_1_m_frequency_s"	:"string",
            "dynamodb_new_image_form_data_m_expected_transaction_from_m_other_bank_acc_l_1_m_source_name_s"	:"string",
            "dynamodb_new_image_form_data_m_expected_transaction_from_m_other_bank_acc_l_1_m_type_s"	:"string",
            "dynamodb_new_image_form_data_m_customer_circumstances_l_2_s"	:"string",
            "dynamodb_new_image_form_data_m_customer_occupations_l_3_s"	:"string",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_1_m_other_value_s"	:"string",
            "dynamodb_new_image_form_data_m_expected_transaction_to_m_use_reasons_l_7_s"	:"string",
            "dynamodb_new_image_form_data_m_supporting_documents_m"	:"string",
            "dynamodb_new_image_form_data_m_supporting_documents_m_three_month_bank_statement_l_1_s"	:"string",
            "dynamodb_new_image_form_data_m_customer_occupations_l_4_s"	:"string",
            "source"	:"string",
            "timestamp_extracted"	:"timestamp",
            "date"	:"date"
        },
        "column_comments":{
           "dynamodb_new_image_created_at_n"	:"",
            "dynamodb_new_image_customer_id_s"	:"",
            "dynamodb_new_image_form_data_m_countries_of_personal_links_l_0_s"	: "the countries that customer has assets there, or employed in ",
            "dynamodb_new_image_form_data_m_customer_circumstances_l_0_s"	: "the employment status of customer if he EMPLOYED, BUSINESS_OWNER, HOMEMAKER, UNEMPLOYED....",
            "dynamodb_new_image_form_data_m_customer_occupations_l_0_s"	:"",
            "dynamodb_new_image_form_data_m_expected_monthly_value_of_transactions_inbound_m_currency_code_s"	: "currency expected that customer will deal with in his transactions monthly",
            "dynamodb_new_image_form_data_m_expected_monthly_value_of_transactions_inbound_m_from_n"	: "the expected minimum amount expected to be transferred to customer from another account",
            "dynamodb_new_image_form_data_m_expected_monthly_value_of_transactions_inbound_m_to_n"	: "the expected maximum amount expected to be transferred by customer from his account to another account",
            "dynamodb_new_image_form_data_m_expected_monthly_value_of_transactions_outbound_m_currency_code_s"	: "currency expected that customer will deal with in his transactions monthly",
            "dynamodb_new_image_form_data_m_expected_monthly_value_of_transactions_outbound_m_from_n"	: "the expected minimum amount expected to be transferred to customer from another account",
            "dynamodb_new_image_form_data_m_expected_monthly_value_of_transactions_outbound_m_to_n"	: "the expected maximum amount expected to be transferred by customer from his account to another account",
            "dynamodb_new_image_form_data_m_pep_positions_l_0_m_pep_position_s"	: "if this customer belong to ROYAL_FAMILY, MILITARY, POLITICIAN, GOVERNMENT, so very important person",
            "dynamodb_new_image_updated_at_n"	:"",
            "dynamodb_new_image_form_data_m_countries_of_personal_links_l_1_s"	: "the countries that customer has assets there, or employed in ",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_0_m_country_code_s"	: "country code of customer's material assets",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_0_m_frequency_s"	: "the expected transactions frequency weekly, monthly",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_0_m_total_income_m_currency_code_s"	: "currency expected that customer will deal with in his material assets",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_0_m_total_income_m_from_n"	:"",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_0_m_total_income_m_to_n"	:"",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_0_m_type_s"	:"",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_1_m_frequency_s"	: "the expected transactions frequency weekly, monthly",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_1_m_total_income_m_currency_code_s"	: "currency expected that customer will deal with in his material assets",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_1_m_total_income_m_from_n"	:"",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_1_m_total_income_m_to_n"	:"",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_1_m_type_s"	:"",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_2_m_country_code_s"	: "country code of customer's material assets",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_2_m_frequency_s"	: "the expected transactions frequency weekly, monthly",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_2_m_total_income_m_currency_code_s"	: "currency expected that customer will deal with in his material assets",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_2_m_total_income_m_from_n"	:"",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_2_m_total_income_m_to_n"	:"",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_2_m_type_s"	:"",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_3_m_country_code_s"	: "country code of customer's material assets",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_3_m_frequency_s"	: "the expected transactions frequency weekly, monthly",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_3_m_total_income_m_currency_code_s"	: "currency expected that customer will deal with in his material assets",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_3_m_total_income_m_from_n"	:"",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_3_m_total_income_m_to_n"	:"",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_3_m_type_s"	:"",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_4_m_country_code_s"	: "country code of customer's material assets",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_4_m_frequency_s"	: "the expected transactions frequency weekly, monthly",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_4_m_total_income_m_currency_code_s"	: "currency expected that customer will deal with in his material assets",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_4_m_total_income_m_from_n"	:"",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_4_m_total_income_m_to_n"	:"",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_4_m_type_s"	:"",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_5_m_country_code_s"	: "country code of customer's material assets",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_5_m_frequency_s"	: "the expected transactions frequency weekly, monthly",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_5_m_total_income_m_currency_code_s"	: "currency expected that customer will deal with in his material assets",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_5_m_total_income_m_from_n"	:"",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_5_m_total_income_m_to_n"	:"",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_5_m_type_s"	:"",
            "dynamodb_new_image_form_data_m_customer_circumstances_l_1_s"	: "the employment status of customer if he EMPLOYED, BUSINESS_OWNER, HOMEMAKER, UNEMPLOYED....",
            "dynamodb_new_image_form_data_m_customer_occupations_l_1_s"	:"",
            "dynamodb_new_image_form_data_m_customer_occupations_l_2_s"	:"",
            "dynamodb_new_image_form_data_m_expected_transaction_from_m_expected_m_amount_m_currency_code_s"	: "currency expected that customer will deal with in his transactions",
            "dynamodb_new_image_form_data_m_expected_transaction_from_m_expected_m_amount_m_from_n"	:  "the expected minimum amount expected to be transferred to customer from another account",
            "dynamodb_new_image_form_data_m_expected_transaction_from_m_expected_m_amount_m_to_n"	: "the expected maximum amount expected to be transferred by customer from his account to another account",
            "dynamodb_new_image_form_data_m_expected_transaction_from_m_expected_m_frequency_s"	: "the expected transactions frequency weekly, monthly",
            "dynamodb_new_image_form_data_m_expected_transaction_from_m_my_bank_acc_l_0_m_amount_m_currency_code_s"	: "currency expected that customer will deal with in his transactions",
            "dynamodb_new_image_form_data_m_expected_transaction_from_m_my_bank_acc_l_0_m_amount_m_from_n"	: "the expected minimum amount expected to be transferred to customer from another account",
            "dynamodb_new_image_form_data_m_expected_transaction_from_m_my_bank_acc_l_0_m_amount_m_to_n"	: "the expected maximum amount expected to be transferred by customer from his account to another account",
            "dynamodb_new_image_form_data_m_expected_transaction_from_m_my_bank_acc_l_0_m_country_code_s"	:"",
            "dynamodb_new_image_form_data_m_expected_transaction_from_m_my_bank_acc_l_0_m_frequency_s"	: "the expected transactions frequency weekly, monthly",
            "dynamodb_new_image_form_data_m_expected_transaction_from_m_my_bank_acc_l_1_m_amount_m_currency_code_s"	:  "currency expected that customer will deal with in his transactions",
            "dynamodb_new_image_form_data_m_expected_transaction_from_m_my_bank_acc_l_1_m_amount_m_from_n"	: "the expected minimum amount expected to be transferred to customer from another account",
            "dynamodb_new_image_form_data_m_expected_transaction_from_m_my_bank_acc_l_1_m_amount_m_to_n"	: "the expected maximum amount expected to be transferred by customer from his account to another account",
            "dynamodb_new_image_form_data_m_expected_transaction_from_m_my_bank_acc_l_1_m_country_code_s"	:"",
            "dynamodb_new_image_form_data_m_expected_transaction_from_m_my_bank_acc_l_1_m_frequency_s"	: "the expected transactions frequency weekly, monthly",
            "dynamodb_new_image_form_data_m_expected_transaction_to_m_amount_m_currency_code_s"	: "currency expected that customer will deal with in his transactions",
            "dynamodb_new_image_form_data_m_expected_transaction_to_m_amount_m_from_n"	: "the expected minimum amount expected to be transferred to customer from another account",
            "dynamodb_new_image_form_data_m_expected_transaction_to_m_amount_m_to_n"	:  "the expected maximum amount expected to be transferred by customer from his account to another account",
            "dynamodb_new_image_form_data_m_expected_transaction_to_m_frequency_s"	: "the expected transactions frequency weekly, monthly",
            "dynamodb_new_image_form_data_m_expected_transaction_to_m_use_reasons_l_0_s"	: "reasons of customer to spend his money",
            "dynamodb_new_image_form_data_m_expected_transaction_to_m_use_reasons_l_1_s"	: "reasons of customer to spend his money",
            "dynamodb_new_image_form_data_m_expected_transaction_to_m_use_reasons_l_2_s"	: "reasons of customer to spend his money",
            "dynamodb_new_image_form_data_m_expected_transaction_to_m_use_reasons_l_3_s"	: "reasons of customer to spend his money",
            "dynamodb_new_image_form_data_m_expected_transaction_to_m_use_reasons_l_4_s"	: "reasons of customer to spend his money",
            "dynamodb_new_image_form_data_m_expected_transaction_to_m_use_reasons_l_5_s"	: "reasons of customer to spend his money",
            "dynamodb_new_image_form_data_m_supporting_documents_m_send_bool"	:"",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_1_m_country_code_s"	: "country code of customer's material assets",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_1_m_total_value_of_properties_m_currency_code_s"	:"",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_1_m_total_value_of_properties_m_from_n"	:"",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_1_m_total_value_of_properties_m_to_n"	:"",
            "dynamodb_new_image_form_data_m_countries_of_personal_links_l_2_s"	: "the countries that customer has assets there, or employed in ",
            "dynamodb_new_image_form_data_m_expected_transaction_from_m_other_bank_acc_l_0_m_amount_m_currency_code_s"	: "currency expected that customer will deal with in his transactions",
            "dynamodb_new_image_form_data_m_expected_transaction_from_m_other_bank_acc_l_0_m_amount_m_from_n"	:  "the expected minimum amount expected to be transferred to customer from another account",
            "dynamodb_new_image_form_data_m_expected_transaction_from_m_other_bank_acc_l_0_m_amount_m_to_n"	:   "the expected maximum amount expected to be transferred by customer from his account to another account",
            "dynamodb_new_image_form_data_m_expected_transaction_from_m_other_bank_acc_l_0_m_country_code_s"	: "country code expected that customer will deal with in his transactions",
            "dynamodb_new_image_form_data_m_expected_transaction_from_m_other_bank_acc_l_0_m_frequency_s"	:   "the expected transactions frequency weekly, monthly",
            "dynamodb_new_image_form_data_m_expected_transaction_from_m_other_bank_acc_l_0_m_source_name_s"	:"",
            "dynamodb_new_image_form_data_m_expected_transaction_from_m_other_bank_acc_l_0_m_type_s"	:"",
            "dynamodb_new_image_form_data_m_pep_positions_l_0_m_state_corporation_name_s"	:"",
            "dynamodb_new_image_form_data_m_supporting_documents_m_certified_assets_l_0_s"	:"",
            "dynamodb_new_image_form_data_m_supporting_documents_m_three_month_bank_statement_l_0_s"	:"",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_0_m_other_value_s"	:"",
            "dynamodb_new_image_form_data_m_expected_transaction_to_m_other_reason_s"	:"",
            "dynamodb_new_image_form_data_m_expected_transaction_to_m_use_reasons_l_6_s"	:"",
            "dynamodb_new_image_form_data_m_countries_of_personal_links_l_3_s"	: "the countries that customer has assets there, or employed in ",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_2_m_other_value_s"	:"",
            "dynamodb_new_image_form_data_m_expected_transaction_from_m_other_bank_acc_l_1_m_amount_m_currency_code_s"	: "currency expected that customer will deal with in his transactions",
            "dynamodb_new_image_form_data_m_expected_transaction_from_m_other_bank_acc_l_1_m_amount_m_from_n"	: "the expected minimum amount expected to be transferred to customer from another account",
            "dynamodb_new_image_form_data_m_expected_transaction_from_m_other_bank_acc_l_1_m_amount_m_to_n"	:  "the expected maximum amount expected to be transferred by customer from his account to another account",
            "dynamodb_new_image_form_data_m_expected_transaction_from_m_other_bank_acc_l_1_m_country_code_s"	: "country code expected that customer will deal with in his transactions",
            "dynamodb_new_image_form_data_m_expected_transaction_from_m_other_bank_acc_l_1_m_frequency_s"	:  "the expected transactions frequency weekly, monthly",
            "dynamodb_new_image_form_data_m_expected_transaction_from_m_other_bank_acc_l_1_m_source_name_s"	:"",
            "dynamodb_new_image_form_data_m_expected_transaction_from_m_other_bank_acc_l_1_m_type_s"	:"",
            "dynamodb_new_image_form_data_m_customer_circumstances_l_2_s"	: "the employment status of customer if he EMPLOYED, BUSINESS_OWNER, HOMEMAKER, UNEMPLOYED....",
            "dynamodb_new_image_form_data_m_customer_occupations_l_3_s"	:"",
            "dynamodb_new_image_form_data_m_countries_of_material_assets_l_1_m_other_value_s"	:"",
            "dynamodb_new_image_form_data_m_expected_transaction_to_m_use_reasons_l_7_s"	:"",
            "dynamodb_new_image_form_data_m_supporting_documents_m"	:"",
            "dynamodb_new_image_form_data_m_supporting_documents_m_three_month_bank_statement_l_1_s"	:"",
            "dynamodb_new_image_form_data_m_customer_occupations_l_4_s"	:"",
            "source"	:"",
            "timestamp_extracted"	:"",
            "date"	:""
        }

    }

}
