config = {
    "queries": {
        "salesforce_account": "q=SELECT Id, Name, CreatedDate FROM Account",
        "salesforce_accounthistory": "q=SELECT Field, OldValue, NewValue, AccountId, CreatedDate FROM AccountHistory",
        "salesforce_cases": """q=SELECT Id, Type, Status, Customer_Reference_Id__c, priority, description,
            CreatedDate, LastModifiedDate, ClosedDate, OwnerId, Origin, ContactId, CaseNumber,
            case_record_type_name__c, Case_RT_Dev_Name__c, Subject, complaint_status__c,
            response_status__c, redress_paid__c, redress_amount__c, Complaint_Root_Cause__c FROM Case""",
        "salesforce_casemilestone": "q=SELECT Id, CaseId, StartDate, TargetDate, CompletionDate, MilestoneTypeId, CreatedDate FROM CaseMilestone",
        "salesforce_contact": """q=select Id, Name, Customer_Cohort__c, Prior_Customer_Cohort__c, Latest_Cohort_Change__c,
            Customer_Intent__c, Intent_Reason__c, Last_Call_Date__c, OCP_Call_1__c, OCP_Call_1_Result__c,
            OCP_Call_1_Date__c, OCP_Call_2__c, OCP_Call_2_Result__c, OCP_Call_2_Date__c, OCP_Call_3__c,
            OCP_Call_3_Result__c, OCP_Call_3_Date__c, Final_Call__c, Final_Call_Attempt_Date__c,
            Final_Call_Projected_Date__c, Final_Call_Result__c, Pending_Final_Call__c,
            FSCS_Eligible__c, Care_Of_Address__c, Beneficiary__c, Sanctioned__c, Gone_Away__c,
            Fraud_Risk__c, Money_Laundering_Risk__c, Legal_Status_Code_Deceased__c,
            Special_Modifications__c, place_of_birth__c, tax_jurisdiction_1__c, jurisdiction_1_id_number__c,
            tax_jurisdiction_2__c, jurisdiction_2_id_number__c, tax_jurisdiction_3__c,
            jurisdiction_3_id_number__c, isUsPerson__c, CreatedDate from Contact""",
        "salesforce_propfin": """q=select id, CaseNumber, Finance_amount__c, Fixed_rate_period__c, Fixed_Profit_Rate__c, Opening_Time__c,
            Document_Validation_Completed_Date__c, Status, Valuation_Stage__c, Valuation_Stage_Completed_Date__c,
            Underwriting_Stage_Completed_Date__c, Offer_Generation_Started_Date__c, Offer_Generation_Completed_Date__c,
            Fee_Withdrawal_Completed_Date__c, Final_Payment_Completed_Date__c, Case_Completion_Completed_Date__c,
            Property_Finance_Type__c, Broker_or_Direct__c, Completion_Date__c, Customer_Reference_Id__c, Collateral_Value__c,
            Application_Partner_name__c, City__c, Postal_code__c, Contact.Brand__c, delivery_country_code__c, Owner.Alias,
            Contact.Birthdate, Repayment_period__c, Application_Fee__c, Legal_Fee__c, Cost_of_Funding__c, Description
            from Case where Property_Finance_Type__c IN ('Rental','Residential') """,
        "salesforce_rework_reason": "q=select Id, Case_Re_work_Reason__c, CreatedDate FROM Case",
        "salesforce_survey": "q=SELECT Id, Name, CreatedDate FROM Survey__c",
        "salesforce_surveytaker": "q=SELECT Id, Name, Survey__c, CreatedDate FROM SurveyTaker__c",
        "salesforce_surveyquestion": "q=SELECT Id, Name, CreatedDate FROM Survey_Question__c",
        "salesforce_surveyquestionresponse": "q=SELECT Id, Name, Question_Type__c, Response__c, Response_Numeric__c, Survey_Question__c, SurveyTaker__c, Survey__c, CreatedDate FROM SurveyQuestionResponse__c",
        "salesforce_user": "q=SELECT Id, Name, CreatedDate FROM User",
        "salesforce_milestonetype": "q=SELECT Id, Name, CreatedDate FROM MilestoneType",
    },
}
